version: '3.8'

services:
  api:
    image: rodcordeiro/raizes-api:latest
    container_name: raizes_api
    restart: unless-stopped
    ports:
      - '3341:80'
    env_file:
      - .env
    networks:
      - raizes
    logging:
      driver: "json-file"  # You can choose a different driver if needed
      options:
        max-size: "5m"  # Maximum size of a single log file
        max-file: "1"    # Maximum number of log files to retain

networks:
  raizes:
    driver: bridge
