version: '3.8'

services:
  api:
    image: rodcordeiro/raizes-api:latest
    container_name: rodcordeiro/raizes-api
    restart: unless-stoped
    ports:
      - '3340:80'
    env_file:
      - .env
    networks:
      - raizes

networks:
  raizes:
    driver: bridge
